table Orders
	lineageTag: 1e4670fa-d703-4f43-aa6b-04a8e91773dc

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 6047d952-ed7a-4d05-9d2b-000be8264fae
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 7a965a1a-cbd4-49ca-83b0-73a7d64f5dcf
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d6f73a1c-b15e-41b0-8be6-c27c0c1702dc
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: c5d53360-fe14-4a26-8a47-bfad966738d5
			defaultHierarchy: LocalDateTable_eebba3a7-5cff-47a4-a6bc-dea0fdd9c2a8.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0a3d6de-6340-4dbf-b19f-0a31a062657d
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 205fa699-e108-47a9-a134-660fa611e08f
			defaultHierarchy: LocalDateTable_13be2223-be5f-4faf-a6eb-c2c11c3f71eb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 2eb37f81-019d-47ab-be35-0835545cfe41
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 8481d124-15ea-4b27-acfe-0c89ad4d5521
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 100e7b87-47a4-4914-9fc8-99ecfafc9cbf
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 418a3bec-e7af-4f39-a398-da8d0e86d9e5
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: edd4d263-23e6-457d-b946-761c7e4cbbf5
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 02a3b07d-932e-4d98-869a-63fc1d22b7eb
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 3c253e83-d722-4377-8acf-979169c36b05
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 335096d4-5a76-4682-9d92-674008eb71ae
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 1c062517-aff9-43b0-8635-4e3e855f2c3f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 021a82e6-f84d-4807-9828-84848dc85c07
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: da65c946-e771-42a5-95ca-655205054836
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: de7c84be-5896-43cf-8c75-cd7c4c70d4a6
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: cbe39187-28cc-4d06-8d6e-8f37e0a9c6ad
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: ce91f6cc-075d-4e23-bf3b-ffb1073f0d5c
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 8f6f9f9e-28e7-488a-8b45-28530399c15c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 291603ed-fb25-4cc8-b7e3-624d4bad85a8
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 1b9b7cd2-8e3e-4a0b-9569-53d3b5c9a92f
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ksaik\OneDrive\Desktop\bullet chart\output\csv_output\Orders.csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

